spring:
  application:
    name: cv-ai-handler
  ai:
    openai:
      api-key: ${OPENAPI_KEY:fake}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
          response-format:
            type: JSON_SCHEMA
            name: CheckCVSchema
            schema:  '{"type":"object","properties":{"steps":{"type":"array","items":{"type":"object","properties":{"explanation":{"type":"string"},"output":{"type":"string"}},"required":["explanation","output"],"additionalProperties":false}},"final_answer":{"type":"string"}},"required":["steps","final_answer"],"additionalProperties":false}'
            strict: true
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID:fake-client-id}
                client-secret: ${GOOGLE_CLIENT_SECRET:fake-client-secret}
                scope:
                  - openid
                  - profile
                  - email

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

clients:
  nofluffjobs:
    base-url: https://nofluffjobs.com

logging:
  level:
    root: INFO